apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-public.fullname" . }}-tx
  labels:
    {{- include "besu-public.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "besu-public.selectorLabels" . | nindent 4 }}
  ports:
  - name: json-rpc
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-public.fullname" . }}-disco-tcp
  labels:
    {{- include "besu-public.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "besu-public.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  ports:
  - name: "rlpx"
    protocol: TCP
    port: 30303
    targetPort: 30303
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-public.fullname" . }}-disco-udp
  labels:
    {{- include "besu-public.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "besu-public.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  ports:
  - name: "rlpx"
    protocol: UDP
    port: 30303
    targetPort: 30303