apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "besu-public.fullname" . }}
  labels:
    {{- include "besu-public.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      {{- include "besu-public.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "besu-public.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "--network={{ .Values.network }}",
            "--data-path=/data",
            "--nat-method=AUTO",
            "--sync-mode=FULL",
            "--discovery-enabled=true",
            "--max-peers=80",
            "--p2p-enabled=true",
            "--p2p-port=30303",
            "--remote-connections-limit-enabled=true",
            "--remote-connections-max-percentage=60",
            "--rpc-http-enabled=true",
            "--rpc-http-host=0.0.0.0",
            "--rpc-http-max-active-connections=80",
            "--rpc-http-port=8545",
            "--rpc-http-api=ADMIN,ETH,NET,TXPOOL,WEB3",
            "--rpc-ws-enabled=false",
            "--host-allowlist=*"
          ]
          ports:
          - name: rpc
            containerPort: 8545
          - name: ws
            containerPort: 8546
          - name: discovery-udp
            containerPort: 30303
            protocol: UDP
          - name: discovery-tcp
            containerPort: 30303
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8545
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ .Chart.Name }}-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: {{ .Values.volumes.class }}
      resources:
        requests:
          storage: {{ .Values.volumes.size }}